winget install --id=Google.Chrome  -e
winget install --id=AnyDeskSoftwareGmbH.AnyDesk  -e
winget install --id=7zip.7zip  -e
winget install --id=ShareX.ShareX  -e
winget install --id=ExpressVPN.ExpressVPN  -e
winget install --id=VideoLAN.VLC  -e
winget install --id=Valve.Steam  -e
winget install --id=GitHub.cli  -e
winget install --id=PuTTY.PuTTY  -e
winget install --id=vim.vim  -e
winget install --id=Toinane.Colorpicker  -e
winget install --id=Microsoft.Teams  -e



winget install --id=Google.Chrome  -e &&
winget install --id=AnyDeskSoftwareGmbH.AnyDesk  -e &&
winget install --id=7zip.7zip  -e &&
winget install --id=ShareX.ShareX  -e &&
winget install --id=ExpressVPN.ExpressVPN  -e &&
winget install --id=VideoLAN.VLC  -e &&
winget install --id=Valve.Steam  -e &&
winget install --id=GitHub.cli  -e &&
winget install --id=PuTTY.PuTTY  -e &&
winget install --id=vim.vim  -e &&
winget install --id=Toinane.Colorpicker  -e && 
winget install --id=Microsoft.Teams  -e
